# Generated by Django 5.1.1 on 2024-11-26 16:12

import django.db.models.deletion
import ticksys.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(default="avatar.jpg", upload_to="Profile_Images"),
                ),
                (
                    "username",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        default=ticksys.models.generate_ticket_number,
                        editable=False,
                        max_length=4,
                        unique=True,
                    ),
                ),
                ("id_number", models.CharField(max_length=20)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Assigned", "Assigned"),
                            ("In Progress", "In Progress"),
                            ("Done", "Done"),
                        ],
                        default="In Progress",
                        max_length=25,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Credentials", "Credentials"),
                            ("Fees & Payments", "Fees & Payments"),
                            ("VClass", "VClass"),
                            ("Transcript", "Transcript"),
                            ("Admission", "Admission"),
                            ("Wi-Fi", "Wi-Fi"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[("Staff", "Staff"), ("Student", "Student")],
                        default="Student",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("Walk-In", "Walk-In"),
                            ("Phone", "Phone"),
                            ("Email", "Email"),
                        ],
                        default="Walk-In",
                        max_length=20,
                    ),
                ),
                ("assigned_to", models.CharField(max_length=30, null=True)),
                ("creator_by", models.CharField(max_length=30, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
