# Generated by Django 5.1.1 on 2024-11-28 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ticksys", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="creator_by",
        ),
    ]
