# Generated by Django 5.1.1 on 2024-10-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticksys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="image",
            field=models.ImageField(default="avatar.jpg", upload_to="Profile_Images"),
        ),
    ]
