# Generated by Django 5.1.1 on 2024-11-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticksys", "0002_remove_ticket_assigned_to_remove_ticket_creator_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="assigned_to",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="creator_by",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
