# Generated by Django 5.1.1 on 2024-11-28 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ticksys", "0003_ticket_assigned_to_ticket_creator_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="creator_by",
            new_name="created_by",
        ),
    ]
