# Generated by Django 5.1.1 on 2024-10-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticksys", "0003_alter_agent_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
