# Generated by Django 5.1.1 on 2024-12-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticksys", "0004_rename_creator_by_ticket_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="client_type",
            field=models.CharField(
                choices=[
                    ("Staff", "Staff"),
                    ("Student", "Student"),
                    ("Other", "Other"),
                ],
                default="Student",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="mode",
            field=models.CharField(
                choices=[
                    ("Walk-In", "Walk-In"),
                    ("Phone", "Phone"),
                    ("Email", "Email"),
                    ("Other", "Other"),
                ],
                default="Walk-In",
                max_length=20,
            ),
        ),
    ]
