# Generated by Django 5.1.1 on 2024-10-23 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ticksys", "0006_ticket_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agent",
            old_name="user",
            new_name="username",
        ),
    ]
