# Generated by Django 5.1.5 on 2025-04-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticksys', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Credentials', 'Credentials'), ('Fees & Payments', 'Fees & Payments'), ('VClass', 'VClass'), ('Transcript', 'Transcript'), ('Admission', 'Admission'), ('Wi-Fi', 'Wi-Fi'), ('AIM App', 'AIM App'), ('Telecel', 'Telecel'), ('Biometric', 'Biometric'), ('Other', 'Other')], max_length=100),
        ),
    ]
