# Generated by Django 5.1.1 on 2024-10-23 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ticksys", "0007_rename_user_agent_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="full_name",
        ),
        migrations.DeleteModel(
            name="TicketLog",
        ),
    ]
