# Generated by Django 5.1.1 on 2024-10-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticksys", "0008_remove_agent_full_name_delete_ticketlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="agent",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
