# Generated by Django 5.1.1 on 2024-10-31 12:12

import ticksys.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticksys", "0009_alter_ticket_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="ticket_number",
            field=models.CharField(
                default=ticksys.models.generate_ticket_number,
                editable=False,
                max_length=4,
                unique=True,
            ),
        ),
    ]
