# Generated by Django 5.1.1 on 2024-10-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticksys", "0010_alter_ticket_ticket_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("Credentials", "Credentials"),
                    ("Fees & Payments", "Fees & Payments"),
                    ("VClass", "VClass"),
                    ("Transcript", "Transcript"),
                    ("Admission", "Admission"),
                    ("Wi-Fi", "Wi-Fi"),
                    ("Other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
