# Generated by Django 5.1.1 on 2024-11-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticksys", "0011_alter_ticket_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="id_number",
            field=models.CharField(max_length=20),
        ),
    ]
