# Generated by Django 5.1.1 on 2024-11-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticksys", "0012_alter_ticket_id_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="client_type",
            field=models.CharField(
                choices=[("Staff", "Staff"), ("Student", "Student")],
                default="Student",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("Assigned", "Assigned"),
                    ("In Progress", "In Progress"),
                    ("Done", "Done"),
                ],
                default="In Progress",
                max_length=20,
            ),
        ),
    ]
